export let allTheCards = [
    {
        name : 'Charizard',
        image : "./images/image1.png",
        type : 'fire',
        hp : 120,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 30,
        id : 1
    },
    {
        name : 'Ninetales',
        image : "./images/image2.png",
        type : 'fire',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 70,
        id : 2
    },
    {
        name : 'Arcanine',
        image : "./images/image3.png",
        type : 'fire',
        hp : 110,
        attackType : 80,
        attack : 50,
        healing : 50,
        thief : 40,
        speed : 60,
        id : 3
    },
    {
        name : 'Charmeleon',
        image : "./images/image4.png",
        type : 'fire',
        hp : 80,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 60,
        speed : 70,
        id : 4
    },
    {
        name : 'Rapidash',
        image : "./images/image5.png",
        type : 'fire',
        hp : 100,
        attackType : 60,
        attack : 70,
        healing : 40,
        thief : 50,
        speed : 80,
        id : 5
    },
    {
        name : 'Magmamar',
        image : "./images/image6.png",
        type : 'fire',
        hp : 80,
        attackType : 70,
        attack : 60,
        healing : 30,
        thief : 30,
        speed : 40,
        id : 6
    },
    {
        name : 'Flareon',
        image : "./images/image7.png",
        type : 'fire',
        hp : 70,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 40,
        speed : 50,
        id : 7
    },
    {
        name : 'Moltres',
        image : "./images/image8.png",
        type : 'fire',
        hp : 140,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 60,
        id : 8
    },
    {
        name : 'Dragonite',
        image : "./images/image9.png",
        type : 'fire',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 40,
        id : 9
    },
    {
        name : 'Blastoise',
        image : "./images/image10.png",
        type : 'water',
        hp : 120,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 30,
        id : 10
    },
    {
        name : 'Golduck',
        image : "./images/image11.png",
        type : 'water',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 70,
        id : 11
    },
    {
        name : 'Poliwrath',
        image : "./images/image12.png",
        type : 'water',
        hp : 110,
        attackType : 80,
        attack : 50,
        healing : 50,
        thief : 40,
        speed : 60,
        id : 12
    },
    {
        name : 'Starmie',
        image : "./images/image13.png",
        type : 'water',
        hp : 80,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 60,
        speed : 70,
        id : 13
    },
    {
        name : 'Seadra',
        image : "./images/image14.png",
        type : 'water',
        hp : 100,
        attackType : 60,
        attack : 70,
        healing : 40,
        thief : 50,
        speed : 80,
        id : 14
    },
    {
        name : 'Lapras',
        image : "./images/image15.png",
        type : 'water',
        hp : 80,
        attackType : 70,
        attack : 60,
        healing : 30,
        thief : 30,
        speed : 40,
        id : 15
    },
    {
        name : 'Vaporeon',
        image : "./images/image16.png",
        type : 'water',
        hp : 70,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 40,
        speed : 50,
        id : 16
    },
    {
        name : 'Articuno',
        image : "./images/image17.png",
        type : 'water',
        hp : 140,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 60,
        id : 17
    },
    {
        name : 'Gyarados',
        image : "./images/image18.png",
        type : 'water',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 40,
        id : 18
    },
    {
        name : 'Venusaur',
        image : "./images/image19.png",
        type : 'plant',
        hp : 120,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 30,
        id : 19
    },
    {
        name : 'Buterfree',
        image : "./images/image20.png",
        type : 'plant',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 70,
        id : 20
    },
    {
        name : 'Arbok',
        image : "./images/image21.png",
        type : 'plant',
        hp : 110,
        attackType : 80,
        attack : 50,
        healing : 50,
        thief : 40,
        speed : 60,
        id : 21
    },
    {
        name : 'Tangela',
        image : "./images/image22.png",
        type : 'plant',
        hp : 80,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 60,
        speed : 70,
        id : 22
    },
    {
        name : 'Beedrill',
        image : "./images/image23.png",
        type : 'plant',
        hp : 100,
        attackType : 60,
        attack : 70,
        healing : 40,
        thief : 50,
        speed : 80,
        id : 23
    },
    {
        name : 'Scyther',
        image : "./images/image24.png",
        type : 'plant',
        hp : 80,
        attackType : 70,
        attack : 60,
        healing : 30,
        thief : 30,
        speed : 40,
        id : 24
    },
    {
        name : 'Nidoqueen',
        image : "./images/image25.png",
        type : 'plant',
        hp : 70,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 40,
        speed : 50,
        id : 25
    },
    {
        name : 'Exeggutor',
        image : "./images/image26.png",
        type : 'plant',
        hp : 140,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 60,
        id : 26
    },
    {
        name : 'Nidoking',
        image : "./images/image27.png",
        type : 'plant',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 40,
        id : 27
    },
    {
        name : 'Machamp',
        image : "./images/image28.png",
        type : 'rock',
        hp : 120,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 30,
        id : 28
    },
    {
        name : 'Sandslash',
        image : "./images/image29.png",
        type : 'rock',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 70,
        id : 29
    },
    {
        name : 'Primeape',
        image : "./images/image30.png",
        type : 'rock',
        hp : 110,
        attackType : 80,
        attack : 50,
        healing : 50,
        thief : 40,
        speed : 60,
        id : 30
    },
    {
        name : 'Dutrio',
        image : "./images/image31.png",
        type : 'rock',
        hp : 80,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 60,
        speed : 70,
        id : 31
    },
    {
        name : 'Golem',
        image : "./images/image32.png",
        type : 'rock',
        hp : 100,
        attackType : 60,
        attack : 70,
        healing : 40,
        thief : 50,
        speed : 80,
        id : 32
    },
    {
        name : 'Kangaskhan',
        image : "./images/image33.png",
        type : 'rock',
        hp : 80,
        attackType : 70,
        attack : 60,
        healing : 30,
        thief : 30,
        speed : 40,
        id : 33
    },
    {
        name : 'Rhydon',
        image : "./images/image34.png",
        type : 'rock',
        hp : 70,
        attackType : 60,
        attack : 50,
        healing : 40,
        thief : 40,
        speed : 50,
        id : 34
    },
    {
        name : 'Kabutops',
        image : "./images/image35.png",
        type : 'rock',
        hp : 140,
        attackType : 80,
        attack : 60,
        healing : 50,
        thief : 50,
        speed : 60,
        id : 35
    },
    {
        name : 'Onix',
        image : "./images/image36.png",
        type : 'rock',
        hp : 100,
        attackType : 70,
        attack : 60,
        healing : 40,
        thief : 50,
        speed : 40,
        id : 36
    },   
]
/* const mewtwo : new Pokemon 
    {
        name : '#mewtoo',
        image : "./images/image37.png",
        type : 'normal',
        hp : 150,
        attackType : 80,
        attack : 70,
        healing : 30,
        thief : 40,
        speed : 50,
    }
] */



